fix: Support std.sort() on arrays of arrays.
The std lib specifies `std.sort` as sorting by operator <= which does
work on arrays. However, sjsonnet didn't implement sorting arrays of
arrays using std.sort:
```
$ sjsonnet-0.5.2 -e '[] <= [1]'
true

$ sjsonnet-0.5.2 -e 'std.sort([[1],[]])'
sjsonnet.Error: Cannot sort array of array
    at [std.sort].(<exec>:1:9)

$ sjsonnet-0.5.2 -e 'std.sort([[1],[]], function(a) a)'
sjsonnet.Error: Cannot sort with key values that are arrays
    at [std.sort].(<exec>:1:9)
```

This PR implements std.sort for arrays of arrays and adds some tests.