Remove a space from the end of a test file name. (#572)
This causes checkout issue on Windows machines.

```
git clone https://github.com/databricks/sjsonnet.git sjsonnet-upstream
Cloning into 'sjsonnet-upstream'...
remote: Enumerating objects: 10577, done.
remote: Counting objects: 100% (48/48), done.
remote: Compressing objects: 100% (33/33), done.
remote: Total 10577 (delta 19), reused 20 (delta 12), pack-reused 10529 (from 1)
Receiving objects: 100% (10577/10577), 3.71 MiB | 7.16 MiB/s, done.
Resolving deltas: 100% (5507/5507), done.
error: invalid path 'sjsonnet/test/resources/go_test_suite/builtinRemoveAt2.jsonnet '
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

---------

Co-authored-by: Dan Stahr <danstahr@microsoft.com>